[package]
name = "desktop"
version = "0.0.0"
edition = "2024"
publish.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
iced = { version = "0.13.1", features = ["default", "image"]  }
convoy = {path = "../lib"}

[lints]
workspace = true
